config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  resources :dummy_users
  resources :users
  get 'users/new'
  root 'static_pages#trending'
  get '/topRated', to: 'static_pages#topRated'
  get '/newArrivals', to: 'static_pages#newArrivals'
  get '/contact', to: 'static_pages#contact'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/add', to: "static_pages#add"
  get '/signup', to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dummy_user.rb
class DummyUser < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
   attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
   class << self
  # Returns the hash digest of the given string.
  def digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
   # Returns a random token.
  def new_token
    SecureRandom.urlsafe_base64
  end
  
   def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, 
    User.digest(remember_token))
   end
   
   # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
     return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
   
    # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
   
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/dummy_users_controller.rb
class DummyUsersController < ApplicationController
  before_action :set_dummy_user, only: [:show, :edit, :update, :destroy]

  # GET /dummy_users
  # GET /dummy_users.json
  def index
    @dummy_users = DummyUser.all
  end

  # GET /dummy_users/1
  # GET /dummy_users/1.json
  def show
  end

  # GET /dummy_users/new
  def new
    @dummy_user = DummyUser.new
  end

  # GET /dummy_users/1/edit
  def edit
  end

  # POST /dummy_users
  # POST /dummy_users.json
  def create
    @dummy_user = DummyUser.new(dummy_user_params)

    respond_to do |format|
      if @dummy_user.save
        format.html { redirect_to @dummy_user, notice: 'Dummy user was successfully created.' }
        format.json { render :show, status: :created, location: @dummy_user }
      else
        format.html { render :new }
        format.json { render json: @dummy_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dummy_users/1
  # PATCH/PUT /dummy_users/1.json
  def update
    respond_to do |format|
      if @dummy_user.update(dummy_user_params)
        format.html { redirect_to @dummy_user, notice: 'Dummy user was successfully updated.' }
        format.json { render :show, status: :ok, location: @dummy_user }
      else
        format.html { render :edit }
        format.json { render json: @dummy_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dummy_users/1
  # DELETE /dummy_users/1.json
  def destroy
    @dummy_user.destroy
    respond_to do |format|
      format.html { redirect_to dummy_users_url, notice: 'Dummy user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dummy_user
      @dummy_user = DummyUser.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dummy_user_params
      params.require(:dummy_user).permit(:email, :password)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end
  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def trending
  end

  def topRated
  end

  def newArrivals
  end
  
  def help
  end
  
  def about
  end
  
  def contact
  end
  
  def add
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
  def new
    @user = User.new
  end
  def create
  @user = User.new(user_params)
  if @user.save
     log_in @user
     flash[:success] = "Welcome to the Sample App!"
    redirect_to @user
  else
    render 'new'
  end
end
private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dummy_users_helper.rb
module DummyUsersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end
   # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.encrypted[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end
  
  # Returns the user corresponding to the remember token cookie.
    def current_user
      if (user_id = session[:user_id])
        @current_user ||= User.find_by(id: user_id)
       elsif (user_id = cookies.encrypted[:user_id])
         raise       # The tests still pass, so this branch is currently untested.
       user = User.find_by(id: user_id)
       if user && user.authenticated?(cookies[:remember_token])
         log_in user
         @current_user = user
       end
     end
    end
  
   # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end
  
   # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
   # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
  # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user.
   def gravatar_for(user, size: 80)
    gravatar_id  = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
 end
end

app/views/dummy_users/_form.html.erb
<%= form_with(model: dummy_user) do |form| %>
  <% if dummy_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dummy_user.errors.count, "error") %> prohibited this dummy_user from being saved:</h2>

      <ul>
        <% dummy_user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/dummy_users/edit.html.erb
<h1>Editing Dummy User</h1>

<%= render 'form', dummy_user: @dummy_user %>

<%= link_to 'Show', @dummy_user %> |
<%= link_to 'Back', dummy_users_path %>

app/views/dummy_users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dummy Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dummy_users.each do |dummy_user| %>
      <tr>
        <td><%= dummy_user.email %></td>
        <td><%= dummy_user.password %></td>
        <td><%= link_to 'Show', dummy_user %></td>
        <td><%= link_to 'Edit', edit_dummy_user_path(dummy_user) %></td>
        <td><%= link_to 'Destroy', dummy_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dummy User', new_dummy_user_path %>

app/views/dummy_users/new.html.erb
<h1>New Dummy User</h1>

<%= render 'form', dummy_user: @dummy_user %>

<%= link_to 'Back', dummy_users_path %>

app/views/dummy_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @dummy_user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @dummy_user.password %>
</p>

<%= link_to 'Edit', edit_dummy_user_path(@dummy_user) %> |
<%= link_to 'Back', dummy_users_path %>

app/views/layouts/_footer.html.erb
    <div class="footer">
        <div class="container">
        
        <div class="top-left">the movie box</div>
        <div class="bottom-left">Designed by Railescu Perla</div>
        <div class="top-right">
          <a <%= link_to "About", about_path %></a>
          <a <%= link_to "Contact", contact_path %></a>
          <a <%= link_to "Help", help_path %></a>
          <a href="https://news.railstutorial.org/">News</a>
        </div>
        </div>
    </div>

app/views/layouts/_header.html.erb
 <div class="header">
        <div class="container">
        <img src="https://www.enlivant.com/~/media/images/blog/blogpost_movies_header_1155x357.ashx">
        <div class="bottom-left">Watch movies now!</div>
        <div class="top-left">the movie box</div>
        <div class="top-right">
          <ul class="nav navbar-nav navbar-right">
              
         
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Help", help_path %></li>
            <% if logged_in? %>
                  <li><%= link_to "Users", "#" %></li>
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Settings", "#" %></li>
                  <li class="divider"></li>
                  <li><%= link_to "Log out", logout_path, method: "delete" %></li>
            <% else %>
              <li><%= link_to "Log in", login_path %></li>
               <li> <%= link_to "Sign up", signup_path %></li>
            <% end %>
          </ul>
        </div>
        </div>
</div>

app/views/layouts/_navigation.html.erb
<div>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
      <div class="navbar">
        
        <div class="add-movie" id="myMovie">
           <a href="/add"><i class="fa fa-plus" aria-hidden="true"></i></a>
        </div>
       <div class="nav navbar-nav navbar-left">
        <a <%= link_to "Trending", root_path %> </a>
        <a <%= link_to "Top Rated", topRated_path %> </a>
        <a <%= link_to "New Arrivals", newArrivals_path %> </a>
      </div>
        <div class="search-container">
            <form action="#">
                <input type="text" placeholder="Search..." name="search">
                <button type="submit"><i class="fa fa-search"></i></button>
            </form>
        </div>
        <div class="dropdown">
        <button class="dropbtn" onclick="myFunction()">Genre
            <i class="fa fa-caret-down"></i>
        </button>
        <div class="dropdown-content" id="myDropdown">
            <a href="/drama">Drama</a>
            <a href="/action">Action</a>
            <a href="/adventure">Adventure</a>
            <a href="/comedy">Comedy</a>
            <a href="/thriller">Thriller</a>
        </div>
      </div> 
    </div>
  </div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script 
src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.j
s">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieBox</title>
    <meta charset="utf-8">
     <meta name="viewport" content="width=device-width, initial-scale=1">
   <%= csrf_meta_tags %>
   <%= csp_meta_tag %>
   <%= stylesheet_link_tag 'application', media: 'all','data-turbolinks-track': 'reload' %>
   <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
   <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/navigation' %>
    <div class="content">
        <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<h1>About</h1>
<p>
  The <a href="https://www.railstutorial.org/"><em>Ruby on 
Rails
  Tutorial</em></a>, part of the
  <a href="https://www.learnenough.com/">Learn Enough</a> 
family of
  tutorials, is a
  <a href="https://www.railstutorial.org/book">book</a> and
  <a href="https://screencasts.railstutorial.org/">screencast 
series</a>
  to teach web development with
  <a href="https://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample app for the tutorial.
</p>

app/views/static_pages/add.html.erb
<h1>Add</h1>
<p>This will be the page for adding new movies</p>

app/views/static_pages/contact.html.erb
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at 
the
  <a href="https://www.railstutorial.org/contact">contact 
page</a>.
</p>

app/views/static_pages/help.html.erb
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="https://www.railstutorial.org/help">Rails Tutorial 
Help page</a>.
  To get help on this sample app, see the
  <a href="https://www.railstutorial.org/book"><em>Ruby on 
Rails Tutorial</em>
  book</a>.
</p>

app/views/static_pages/newArrivals.html.erb
    <div class="trending"> 
        <div class="row">
        <div class="column">
            <div class="movie zoom">
                <img src="https://images-na.ssl-images-amazon.com/images/I/91WNnQZdybL._AC_SL1500_.jpg" alt="Image">
                <h1>name</h1>
                <h2>name</h2>
            </div>
        </div>
        <div class="column">
            <div class="movie zoom">
                <img src="https://images-na.ssl-images-amazon.com/images/I/91WNnQZdybL._AC_SL1500_.jpg" alt="Image">
                <h1>name</h1>
                <h2>name</h2>
            </div>
        </div>
        <div class="column">
            <div class="movie zoom">
                <img src="https://images-na.ssl-images-amazon.com/images/I/91WNnQZdybL._AC_SL1500_.jpg" alt="Image">
                <h1>name</h1>
                <h2>name</h2>
            </div>
        </div>
        <div class="column">
            <div class="movie zoom">
                <img src="https://images-na.ssl-images-amazon.com/images/I/91WNnQZdybL._AC_SL1500_.jpg" alt="Image">
                <h1>name</h1>
                <h2>name</h2>
            </div>
        </div>
        <div class="column">
            <div class="movie zoom">
                <img src="https://images-na.ssl-images-amazon.com/images/I/91WNnQZdybL._AC_SL1500_.jpg" alt="Image">
                <h1>name</h1>
                <h2>name</h2>
            </div>
        </div>
        <div class="column">
            <div class="movie zoom">
                <img src="https://images-na.ssl-images-amazon.com/images/I/91WNnQZdybL._AC_SL1500_.jpg" alt="Image">
                <h1>name</h1>
                <h2>name</h2>
            </div>
        </div>
        </div>
    </div>

app/views/static_pages/topRated.html.erb
    <div class="trending"> 
        <div class="row">
        <div class="column">
            <div class="movie zoom">
                <img src="https://images-na.ssl-images-amazon.com/images/I/91WNnQZdybL._AC_SL1500_.jpg" alt="Image">
                <h1>name</h1>
                <h2>name</h2>
            </div>
        </div>
        <div class="column">
            <div class="movie zoom">
                <img src="https://images-na.ssl-images-amazon.com/images/I/91WNnQZdybL._AC_SL1500_.jpg" alt="Image">
                <h1>name</h1>
                <h2>name</h2>
            </div>
        </div>
        <div class="column">
            <div class="movie zoom">
                <img src="https://images-na.ssl-images-amazon.com/images/I/91WNnQZdybL._AC_SL1500_.jpg" alt="Image">
                <h1>name</h1>
                <h2>name</h2>
            </div>
        </div>
        <div class="column">
            <div class="movie zoom">
                <img src="https://images-na.ssl-images-amazon.com/images/I/91WNnQZdybL._AC_SL1500_.jpg" alt="Image">
                <h1>name</h1>
                <h2>name</h2>
            </div>
        </div>
        <div class="column">
            <div class="movie zoom">
                <img src="https://images-na.ssl-images-amazon.com/images/I/91WNnQZdybL._AC_SL1500_.jpg" alt="Image">
                <h1>name</h1>
                <h2>name</h2>
            </div>
        </div>
        <div class="column">
            <div class="movie zoom">
                <img src="https://images-na.ssl-images-amazon.com/images/I/91WNnQZdybL._AC_SL1500_.jpg" alt="Image">
                <h1>name</h1>
                <h2>name</h2>
            </div>
        </div>
        </div>
    </div>

app/views/static_pages/trending.html.erb
    <div class="trending"> 
        <div class="row">
        <div class="column">
            <div class="movie zoom">
                <img src="https://images-na.ssl-images-amazon.com/images/I/91WNnQZdybL._AC_SL1500_.jpg" alt="Image">
                <h1>name</h1>
                <h2>name</h2>
            </div>
        </div>
        <div class="column">
            <div class="movie zoom">
                <img src="https://images-na.ssl-images-amazon.com/images/I/91WNnQZdybL._AC_SL1500_.jpg" alt="Image">
                <h1>name</h1>
                <h2>name</h2>
            </div>
        </div>
        <div class="column">
            <div class="movie zoom">
                <img src="https://images-na.ssl-images-amazon.com/images/I/91WNnQZdybL._AC_SL1500_.jpg" alt="Image">
                <h1>name</h1>
                <h2>name</h2>
            </div>
        </div>
        <div class="column">
            <div class="movie zoom">
                <img src="https://images-na.ssl-images-amazon.com/images/I/91WNnQZdybL._AC_SL1500_.jpg" alt="Image">
                <h1>name</h1>
                <h2>name</h2>
            </div>
        </div>
        <div class="column">
            <div class="movie zoom">
                <img src="https://images-na.ssl-images-amazon.com/images/I/91WNnQZdybL._AC_SL1500_.jpg" alt="Image">
                <h1>name</h1>
                <h2>name</h2>
            </div>
        </div>
        <div class="column">
            <div class="movie zoom">
                <img src="https://images-na.ssl-images-amazon.com/images/I/91WNnQZdybL._AC_SL1500_.jpg" alt="Image">
                <h1>name</h1>
                <h2>name</h2>
            </div>
        </div>
        </div>
    </div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'shared/error_messages' %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
       <h1>
         <%= gravatar_for @user %>
         <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>